version: '3.8'

services:
  # Сервис для FastAPI
  app:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    environment:
      - PYTHONUNBUFFERED=1

  # Сервис для Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    depends_on:
      - app